### ISSUE TITLE
[greencheck] Update codestyle to PSR2/Symfony

### ISSUE THREAD

**Issue by arendjantetteroo** [thegreenwebfoundation/greencheck-api#3]
Some parts still look like the php4 age with _ for properties. 

- [ ] add a pre-commit hook, maybe using [pre-commit](https://github.com/pre-commit/pre-commit)

**Comment by mrchrisadams** [comment]
OK @arendjantetteroo as far as I can tell, this would largely be a case of running part of the codebase through something like [PHP codesniffer](https://github.com/squizlabs/PHP_CodeSniffer), right?

Once we have this, we can then think about either adding it to CI pipeline, or locally with something like [Pre-Commit](https://github.com/pre-commit/pre-commit)

**Comment by arendjantetteroo** [comment]
Some of it might be automatically fixed by php-cs-fixer maybe, others might need some manual changes. 

pre-commit should help yes.

**Comment by arendjantetteroo** [comment]
Code style should be ok now (except for maybe a few small issues here and there). 

Still to do : add a pre-commit hook.

**Comment by mrchrisadams** [comment]
Hey @arendjantetteroo , I'm not familiar enough with php to know the idiomatic way to do this, but the approach I see with phpunit, is that installing it with composer gives us `./bin/phpunit` that we can call easily.

Do we have an equivalent for code style in php, like `./bin/some-handy-binary` ?

If so, I'm thinking that, plus some read me instruction on how to set up pre-commit might be sufficient.

WDYT?

**Comment by arendjantetteroo** [comment]
php-cs-fixer is the name :)
