### ISSUE TITLE
Make the batch logger quicker by avoiding doctrine orm + allowing a table with concurrent inserts

### ISSUE THREAD

**Issue by arendjantetteroo** [thegreenwebfoundation/greencheck-api#36]
The batch logger is now using doctrine and a flush every 50 records. This works but is rather slow and gets slower with each record to be processed by the logger. If we can avoid doctrine and just use sql inserts which we can batch we should be able to process way more messages with one worker. 

At a later point we could see if we can make the table we write all these requests to allow multi writes so we can process with multiple workers. Currently we use one to avoid concurrency issues on the `greencheck` table

**Comment by mrchrisadams** [comment]
@arendjantetteroo on this bit here:

> At a later point we could see if we can make the table we write all these requests to allow multi writes so we can process with multiple workers. Currently we use one to avoid concurrency issues on the greencheck table

Can you elaborate on this a bit? I'm not familiar enough with MySQL or the internals, to understand properties of of greencheck table prevent multiple workers writing to it.

I understand it's a MyISAM table, but the docs here suggest we might be able to do concurrent inserts into that table anyway
https://dev.mysql.com/doc/refman/5.7/en/concurrent-inserts.html

**Comment by mrchrisadams** [comment]
Ah, this SO qn here has shed some light for me:

https://stackoverflow.com/questions/32087233/how-does-mysql-handle-concurrent-inserts

> MySQL does support parallel data inserts into the same table.
>
> But approaches for concurrent read/write depends upon storage engine you use.
> InnoDB
> 
> MySQL uses row-level locking for InnoDB tables to support simultaneous write access by multiple sessions, making them suitable for multi-user, highly concurrent, and OLTP applications.
> MyISAM
> 
> MySQL uses table-level locking for MyISAM, MEMORY, and MERGE tables, allowing only one session to update those tables at a time, making them more suitable for read-only, read-mostly, or single-user applications
> 
> But, the above mentioned behavior of MyISAM tables can be altered by _concurrent_insert_ system variable in order to achieve concurrent write.

If we're using MySQL 5.6, it makes me think that [_concurrent_insert_][concurrent_insert] might buy us some time.

[concurrent_insert]:https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_concurrent_insert

**Comment by arendjantetteroo** [comment]
yep, it's 5.6.
