### ISSUE TITLE
Add public IP ranges for cloud giants - Microsoft

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/greencheck-api#59]
After reading over the Github Actions documentation I found out that they list their public IP ranges too of the machines running in Azure's various regions.

These are updated each week, so like we do with Amazon in #18, I think we can do the same for Microsoft's cloud too. This would mean people building in these regions would get the smiley green badges without loads of tiresome manually  updates.

The link to the JSON list of IP ranges and services is below:

https://www.microsoft.com/en-us/download/details.aspx?id=56519

What we do for AWS, we should do for Microsoft too, with a different JSON parser as the data is likely to be structured differently, even we we're still dealing with regions, ASNs and IP ranges.

**Comment by arendjantetteroo** [comment]
@mrchrisadams should this issue stay here or move to the admin repo?

**Comment by mrchrisadams** [comment]
Yes, this is correct. closing in favour of the issue below:

https://github.com/thegreenwebfoundation/admin-portal/issues/189
