### ISSUE TITLE
Rename this project to represent its role

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/greencheck-api#60]
@arendjantetteroo the name `thegreenwebfoundation /
thegreenwebfoundation` isn't all that helpful for new users, and is a bit confusing when managing issues too.

Given that this repo contains the greencheck API, and we have a separate _admin_ repo (with an equally poor repo name right now…), how do you feel about renaming this to something more descriptive- maybe greencheck-api?

I'd like to rename the django based admin project something different than `thegreenwebfoundation/greenwebfoundation-admin/`, as that's not all that descriptive either, but I'm not sure yet.

Suggestions for both welcome…

**Comment by arendjantetteroo** [comment]
Yes, makes sense. When i started this i had expected to have a monorepo for everything we do at the greenweb, but that seems not really realistic or a good idea anyway. 

greencheck-api seems fine for me. 

for the admin, maybe something with hoster-portal?

**Comment by arendjantetteroo** [comment]
@mrchrisadams changed to greencheck-api. will work tomorrow on the deploy scripts.

**Comment by mrchrisadams** [comment]
I've updated the django project to `hosting-portal`.

There's an issue here now for updating the deployment scripts. Given they both use similar ansible playbooks, it might be possible to end up with a nice zero-touch deployment pipeline for both projects.

https://github.com/thegreenwebfoundation/admin-portal/issues/73

**Comment by arendjantetteroo** [comment]
Deploy scripts updated. I think we can close this one now.
