### ISSUE TITLE
The greencheck API seems to respond randomly with BrinkmanIT for any domain

### ISSUE THREAD

**Issue by KuSh** [thegreenwebfoundation/greencheck-api#77]
See for example a request I did on your [API doc](https://admin.thegreenwebfoundation.org/api-docs/) :

`date: Tue,22 Oct 2024 14:22:55 GMT`
```json
{
  "url": "scalingo.io",
  "hosted_by": "BrinkmanIT",
  "hosted_by_website": "https://www.brinkhost.nl/",
  "partner": null,
  "green": true,
  "hosted_by_id": 1251,
  "modified": "2024-10-22T14:22:50",
  "supporting_documents": []
}
```
![image](https://github.com/user-attachments/assets/9d8c7a23-3e0d-4670-8386-be5241a6d7cd)

And another I did directly in my brother at the same time :

`date: Tue, 22 Oct 2024 14:22:49 GMT`
```json
{"green":false,"url":"scalingo.io","data":false}
```

![image](https://github.com/user-attachments/assets/5cdf3a07-2968-481e-ab3a-4d712c5c3ebd)
![image](https://github.com/user-attachments/assets/e56515f7-a56c-4187-bd3a-fbb48dac2434)

I have the same response for many other urls :
- www.pierre-fabre.com
- many ademe.fr subdomains
- many scalingo.io subdomains
- ...

It seems to be linked with their hosting solution (Platform.sh or Scalingo) as I also get that result when I call greencheck directly on scalingo.io or platform.sh :

```json
{
  "url": "scalingo.io",
  "hosted_by": "BrinkmanIT",
  "hosted_by_website": "https://www.brinkhost.nl/",
  "partner": null,
  "green": true,
  "hosted_by_id": 1251,
  "modified": "2024-10-22T14:22:50",
  "supporting_documents": []
}
```

```json
{
  "url": "Platform.sh",
  "hosted_by": "BrinkmanIT",
  "hosted_by_website": "https://www.brinkhost.nl/",
  "partner": null,
  "green": true,
  "hosted_by_id": 1251,
  "modified": "2024-10-16T18:45:52",
  "supporting_documents": []
}
```

Looking at [BrinkmanIT](https://www.brinkhost.nl/) website I don't find any evidence of a link between them and platform.sh or Scalingo. No evidence neither when searching on internet.

Could that be a bug in some of greencheck api backends ?

**Comment by fershad** [comment]
Thanks @KuSh. ​There is an abnormally large IP range in attached the Brinkman IT listing that I have could be causing this. I have deactivated that range while I follow up with them.

**Comment by mrchrisadams** [comment]
I think we've resolved this now, and made changes in the admin to catch this in future. There may be a piece of work to add this to the form wizard when we revisit that work later in Q1 2025
